#!/usr/bin/env python3
import sys
from curses import wrapper
from canmon import CanMonitor
from canmon.common import tables_path, dev_names_path
from canmon.utilities import load_config


def main(args):
    # Attempt to load the devices config
    try:
        dev_names = load_config(dev_names_path)
    except FileNotFoundError:
        print('fatal: failed to open devices config!')
        sys.exit(-1)

    # Attemt to open the tables config
    try:
        table_schema = load_config(tables_path)
    except FileNotFoundError:
        print('fatal: failed to open devices config!')
        sys.exit(-1)

    try:
        canmonitor = CanMonitor(dev_names, table_schema)
        wrapper(canmonitor.start)
    finally:
        canmonitor.stop()
        print('Goodbye!')


if __name__ == "__main__":
    main(sys.argv[1:])
