#!/usr/bin/env python3
from json.decoder import JSONDecodeError
from curses import wrapper
from canmon import CanMonitor
from canmon.common import layout_path, dev_names_path
from canmon.utilities import prime_config_dir, load_config, config_factory


def main(window):
    # Guarentee the config directory exists
    prime_config_dir()

    # Attempt to load the devices config
    try:
        dev_names = load_config(dev_names_path)
    except FileNotFoundError:
        config_factory(dev_names_path)
        dev_names = load_config(dev_names_path)
    except JSONDecodeError:
        print('fatal: malformed config file: ' + dev_names_path)

    # Attemt to open the tables config
    try:
        table_schema = load_config(layout_path)
    except FileNotFoundError:
        config_factory(layout_path)
        table_schema = load_config(layout_path)
    except JSONDecodeError:
        print('fatal: malformed config file: ' + layout_path)

    try:
        canmonitor = CanMonitor(window, dev_names, table_schema)
        canmonitor.start()
    except KeyboardInterrupt:
        print('Requesting application stop...')
    finally:
        canmonitor.stop()


if __name__ == "__main__":
    wrapper(main)
